# Generated by Django 4.1.4 on 2022-12-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="cidadao",
            fields=[
                ("nome_completo", models.CharField(max_length=50)),
                ("nome_social", models.CharField(max_length=50)),
                (
                    "cpf",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fk",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nasc", models.DateField(verbose_name="nasc")),
                ("estado", models.CharField(max_length=2, verbose_name="estado")),
                ("senha", models.CharField(max_length=12, verbose_name="senha")),
                (
                    "perfil",
                    models.CharField(
                        choices=[("PROF", "Professor"), ("ALU", "Aluno")], max_length=4
                    ),
                ),
            ],
        ),
    ]
