# Generated by Django 4.1.4 on 2022-12-27 15:48

from django.db import migrations, models
import forum.manager


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser", managers=[("objects", forum.manager.UserManager()),],
        ),
        migrations.AddField(
            model_name="customuser",
            name="cidade",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="estado",
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name="customuser", name="nasc", field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nome_social",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="perfil",
            field=models.CharField(
                choices=[("PROF", "Professor"), ("ALU", "Aluno")],
                default="ALU",
                max_length=4,
            ),
        ),
    ]
