# Generated by Django 4.1.4 on 2023-01-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topico",
            name="estado",
            field=models.CharField(
                choices=[("ATV", "Ativado"), ("TRC", "Trancado")],
                default="ATV",
                max_length=4,
            ),
        ),
    ]
