# Generated by Django 4.1.4 on 2022-12-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_customuser_managers_customuser_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nome_completo",
            field=models.CharField(default=None, max_length=60),
        ),
    ]
