# Generated by Django 4.1.4 on 2023-01-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_resposta_nome_autor_subforum_nome_autor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resposta",
            name="nome_social",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AddField(
            model_name="subforum",
            name="nome_social",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AddField(
            model_name="topico",
            name="nome_social",
            field=models.CharField(default=" ", max_length=50),
        ),
    ]
