# Generated by Django 4.1.4 on 2023-01-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_resposta_nome_social_subforum_nome_social_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="topico", name="nome_social",),
    ]
