# Generated by Django 4.1.4 on 2022-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_alter_customuser_cidade_alter_customuser_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="estado",
            field=models.CharField(default=None, max_length=2),
        ),
    ]
