# Generated by Django 4.1.4 on 2023-01-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_remove_topico_nome_social"),
    ]

    operations = [
        migrations.DeleteModel(name="AlunosVinculados",),
    ]
