# Generated by Django 4.1.4 on 2022-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_alter_customuser_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cidade",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nome_completo",
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nome_social",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="perfil",
            field=models.CharField(
                choices=[("PROF", "Professor"), ("ALU", "Aluno")],
                default=None,
                max_length=4,
            ),
        ),
    ]
