# Generated by Django 4.1.4 on 2023-01-07 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_remove_topico_nome_social"),
    ]

    operations = [
        migrations.CreateModel(
            name="VinculoSubforum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cod_subforum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.subforum"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="AlunosVinculados",),
    ]
