# Generated by Django 4.1.4 on 2022-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_alter_customuser_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nome_completo",
            field=models.CharField(default=" ", max_length=60),
        ),
    ]
