# Generated by Django 4.1.4 on 2022-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0009_alter_customuser_nasc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="perfil",
            field=models.CharField(
                choices=[("PROF", "Professor"), ("ALU", "Aluno")],
                default="ALU",
                max_length=4,
            ),
        ),
    ]
