# Generated by Django 4.1.4 on 2022-12-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_alter_customuser_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(default=" ", max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Subforum",
            fields=[
                ("cod_subforum", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(default=" ", max_length=120)),
                ("descricao", models.CharField(default=" ", max_length=512)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ATV", "Ativado"), ("TRC", "Trancado")],
                        default="ATV",
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nasc",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Topico",
            fields=[
                ("cod_topico", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(default=" ", max_length=120)),
                ("descricao", models.CharField(default=" ", max_length=512)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "autor_topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cod_subforum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.subforum"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subforum",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subforum",
            name="cat_subforum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="forum.categoria"
            ),
        ),
    ]
