# Generated by Django 4.1.4 on 2022-12-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_categoria_subforum_alter_customuser_nasc_topico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlunosVinculados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="topico",
            name="autor_topico",
            field=models.CharField(max_length=60),
        ),
    ]
