# Generated by Django 4.1.4 on 2022-12-30 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0012_alunosvinculados_alter_topico_autor_topico"),
    ]

    operations = [
        migrations.RemoveField(model_name="topico", name="autor_topico",),
        migrations.AddField(
            model_name="topico",
            name="autor",
            field=models.ForeignKey(
                #default=" ",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
