# Generated by Django 4.1.4 on 2022-12-30 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0013_remove_topico_autor_topico_topico_autor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(default=" ", max_length=512)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cod_topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.topico"
                    ),
                ),
            ],
        ),
    ]
