# Generated by Django 4.1.4 on 2022-12-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0014_resposta"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="id",),
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                max_length=11, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
