# Generated by Django 4.1.4 on 2022-12-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0015_remove_customuser_id_alter_customuser_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
