# Generated by Django 4.1.4 on 2022-12-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0016_alter_customuser_cpf"),
    ]

    operations = [
        migrations.DeleteModel(name="Resposta",),
    ]
